### PR TITLE
clippy: Fix `let_and_return` lint in neon.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by bitshifter** [comment]
This one is generated so you'll need to update the template and rerun codegen, or I can do it if you prefer.

**Comment by bitshifter** [comment]
Looking at the template it might be easier to add `It might be easier to add `#[allow(clippy::let_and_return)]` here.

**Comment by waywardmonkeys** [comment]
I just updated the template and thought about the same thing ... but tried this as well. What do you think?

**Comment by bitshifter** [comment]
That works as well :)

**Comment by waywardmonkeys** [comment]
I had also tried just doing `unsafe { ... } & 0x7` but that didn't looked bad to me in the generated re-formatted code.

**Comment by waywardmonkeys** [comment]
And the reason this didn't get picked up by CI is that clippy is just run on the ubuntu build, not all platforms / configs.

**Comment by bitshifter** [comment]
Ah, I was wondering. I should do something about that.

**Pull request merged**
