### PR TITLE
Fix bad Matrix4x4 determinant in sse&wasm implementations

### LINKED ISSUE #279: Wrong determinant calculation for `Mat4`
This test case fails:

```rust
#[test]
fn test_determinant() {
    use glam::{Mat4, Vec4};
    let matrix = Mat4::from_cols(
        Vec4::new(0.0, 0.0, 0.0, 1.0),
        Vec4::new(1.0, 0.0, 0.0, 0.0),
        Vec4::new(0.0, 0.0, 1.0, 0.0),
        Vec4::new(0.0, 1.0, 0.0, 0.0),
    );
    assert_eq!(matrix.determinant(), 1.0);
}
```

The result of the determinant calculation in glam is `0.0`, while it should be `1.0`.

### PR DESCRIPTION
**Pull request by TethysSvensson**
This fixes #279.

There is a bug in the determinant calculation using SSE.

The code from glm was not translated correctly.

### CODE REVIEW

**Comment by TethysSvensson** [comment]
It seems there was the same problem in the wasm implementation, which made the CI fail. I think I fixed the problem there as well, but I am unable to run the test suite locally.

**Comment by bitshifter** [comment]
Awesome, thanks for the fix!

**Comment by TethysSvensson** [comment]
@bitshifter Would you mind doing a new release for this?

**Comment by bitshifter** [comment]
@TethysSvensson just released 0.20.3

**Pull request merged**
