### PR TITLE
fix(f32): is_normalized

### PR DESCRIPTION
**Pull request by 5-23**

### CODE REVIEW

**Comment by 5-23** [comment]
image
XD

**Comment by bitshifter** [comment]
Can you please provide a text description for this and update the tests to include the problem you are fixing

**Comment by 5-23** [comment]
> Can you please provide a text description for this and update the tests to include the problem you are fixing

This code eliminates the error that occurs when the length of vec2 is smaller than the minimum value of f32.

**Comment by 5-23** [comment]
While playing with bevy_xpbd, an error occurred, so I searched for it and estimated the cause.

**Comment by bitshifter** [comment]
I don't really think this change makes sense, at least it is inefficient because the code now calculates length_squared twice, adds an if statement and it makes the check potentially too narrow, but I would like to better understand the problem you are trying to fix.

**Comment by bitshifter** [comment]
Closing this, if you can provide some example code showing how is_normalized is doing something unexpected please open an issue.

**Pull request closed without merging**
