### PR TITLE
Add Quat::angle_between

### PR DESCRIPTION
**Pull request by emilk**
This is very similar to the existing `Vec3::angle_between`

### CODE REVIEW

**Comment by emilk** [comment]
I'll cool down with the unsolicited PR:s after this one, I promise!

**Comment by bitshifter** [comment]
Are these all things that you are using at Embark, or from other projects?

**Comment by bitshifter** [comment]
Would be good to add to `CHANGELOG.md` as well

**Comment by emilk** [comment]
These are things we're using at Embark.

**Review by bitshifter — APPROVED** [review]

**Pull request merged**
