### PR TITLE
Element-wise sum and product for vectors. (#462)

### PR DESCRIPTION
**Pull request by Ababwa**

### CODE REVIEW

**Comment by Ababwa** [comment]
Compiler can't find `Which` in `std::simd`. Not sure what to do here. https://doc.rust-lang.org/std/simd/enum.Which.html

**Comment by bitshifter** [comment]
The docs might be out of date. I think they got rid of First and Second, numbers should be the same as what wasm uses now.

**Comment by Ababwa** [comment]
Made some revisions. Should be good now.

**Comment by Ababwa** [comment]
Closing to change fork branch.

**Pull request closed without merging**
